version: '3.4'

services:
  projetofinalcompass:
    image: projetofinalcompass
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:80
